# Este arquivo define dois serviços: um banco de dados PostgreSQL (db) e uma aplicação Python (app),
# que roda o script main.py após se conectar ao banco.

version: '3.8'

services:
  db:
    image: postgres:17              # Usa a imagem oficial do PostgreSQL versão 17
    container_name: pg_container    # Nome do container do banco de dados

    environment:
      POSTGRES_USER: postgres       # Usuário do banco
      POSTGRES_PASSWORD: 1234       # Senha do banco
      POSTGRES_DB: exportacao-graos # Nome do banco que será criado ao iniciar o container

    volumes:
      - pgdata:/var/lib/postgresql/data # Volume persistente dos dados do PostgreSQL

    ports:
      - "5432:5432" # Expõe a porta 5432 do container para o host

    networks:
      - backend # Usa a rede definida abaixo


  app:
    build:
      context: .                    # Diretório atual como contexto de build
      dockerfile: Dockerfile        # Usa o Dockerfile presente no mesmo diretório
    container_name: app_container   # Nome do container da aplicação
    depends_on:
      - db # Aguarda o container 'db' subir antes de iniciar
    environment:
      DB_HOST: localhost            # 'localhost' se refere à máquina host
      DB_PORT: 5433                 # Porta usada no seu script para conectar ao PostgreSQL
      DB_NAME: exportacao-graos     
      DB_USER: postgres
      DB_PASSWORD: 1234
    volumes:
      - .:/app                      # Monta o diretório atual dentro do container
    working_dir: /app               # Define o diretório de trabalho no container
    command: python main.py         # Comando executado ao iniciar o container
    networks:
      - backend                     # Rede compartilhada com o banco de dados